# Generated by Django 3.2.5 on 2021-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='good_quantity',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Количество товара'),
        ),
    ]
